// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("DoubleCache")]
[assembly: AssemblyDescriptionAttribute("Layered distributed cache-aside implementation")]
[assembly: GuidAttribute("505f87a8-3062-4070-af1f-cd7358ccd06a")]
[assembly: AssemblyProductAttribute("DoubleCache")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0-beta.6")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
[assembly: AssemblyMetadataAttribute("githash","dec9f54eb2a4442298e2681b6ba85c674addc4cc")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "DoubleCache";
        internal const System.String AssemblyDescription = "Layered distributed cache-aside implementation";
        internal const System.String Guid = "505f87a8-3062-4070-af1f-cd7358ccd06a";
        internal const System.String AssemblyProduct = "DoubleCache";
        internal const System.String AssemblyVersion = "2.0.0";
        internal const System.String AssemblyInformationalVersion = "2.0.0-beta.6";
        internal const System.String AssemblyFileVersion = "2.0.0";
        internal const System.String AssemblyMetadata_githash = "dec9f54eb2a4442298e2681b6ba85c674addc4cc";
    }
}
