// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("DoubleCache")]
[assembly: AssemblyDescriptionAttribute("Layered distributed cache-aside implementation")]
[assembly: GuidAttribute("505f87a8-3062-4070-af1f-cd7358ccd06a")]
[assembly: AssemblyProductAttribute("DoubleCache")]
[assembly: AssemblyVersionAttribute("1.5.0")]
[assembly: AssemblyInformationalVersionAttribute("1.5.0")]
[assembly: AssemblyFileVersionAttribute("1.5.0")]
[assembly: AssemblyMetadataAttribute("githash","54c5137866e8115563eb483c019c1ee0fb4c509e")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "DoubleCache";
        internal const System.String AssemblyDescription = "Layered distributed cache-aside implementation";
        internal const System.String Guid = "505f87a8-3062-4070-af1f-cd7358ccd06a";
        internal const System.String AssemblyProduct = "DoubleCache";
        internal const System.String AssemblyVersion = "1.5.0";
        internal const System.String AssemblyInformationalVersion = "1.5.0";
        internal const System.String AssemblyFileVersion = "1.5.0";
        internal const System.String AssemblyMetadata_githash = "54c5137866e8115563eb483c019c1ee0fb4c509e";
    }
}
